// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/hello": {
            "get": {
                "description": "A simple greeting earthlings!",
                "produces": [
                    "text/plain"
                ],
                "responses": {
                    "200": {
                        "description": "Hello World!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/ping": {
            "get": {
                "description": "Check API health",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Stats"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.MemStats": {
            "type": "object",
            "properties": {
                "alloc": {
                    "type": "number"
                },
                "gc_cycle": {
                    "type": "integer"
                },
                "gc_last": {
                    "type": "integer"
                },
                "gc_next": {
                    "type": "integer"
                },
                "sys": {
                    "type": "number"
                }
            }
        },
        "v1.Stats": {
            "type": "object",
            "properties": {
                "memstats": {
                    "$ref": "#/definitions/v1.MemStats"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "A-API",
	Description:      "This is a simple REST API for the Boiler Plate API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
